#!/bin/bash
sudo apt install apache2 -y
sudo apt install bind9 -y
sudo apt install isc-dhcp-server -y
sudo apt install haproxy -y
sudo apt install squid -y
sudo apt install samba -y
sudo apt install nfs-kernel-server -y
sudo apt install vsftpd -y
sudo apt install net-tools -y
